#define RENDERING_SCREEN -1
#define LANDING_SCREEN 0
#define RIDGES_SCREEN 1
#define PEAKS_SCREEN 2
#define RIVERS_SCREEN 3
#define BASINS_SCREEN 4
#define LOADING_SCREEN 5

#define RIDGES 0
#define PEAKS 1
#define RIVERS 2
#define BASINS 3

#define MESH 0
#define SUN 1
#define SPLASHSCREEN 2
#define CANVAS 3
#define SKETCH 4

#define LOS_DISTANCE 2

#define LEFT_SKETCH_BORDER 0.063
#define RIGHT_SKETCH_BORDER 0.482
#define TOP_SKETCH_BORDER 0.13
#define BOTTOM_SKETCH_BORDER 0.87