#define RENDERING_SCREEN -1
#define LANDING_SCREEN 0
#define RIDGES_SCREEN 1
#define PEAKS_SCREEN 2
#define RIVERS_SCREEN 3
#define BASINS_SCREEN 4
#define LOADING_SCREEN 5

#define RIDGES 0
#define PEAKS 1
#define RIVERS 2
#define BASINS 3

#define MESH 0
#define SPLASHSCREEN 1
#define CANVAS 2
#define SKYDOME 3
#define SUN 4
#define MOON 5
#define WATER 6
#define VEGETATION 7
#define SKETCH 8

#define LOS_DISTANCE 2

#define BUSH_SIZE 400

#define LEFT_SKETCH_BORDER 0.063
#define RIGHT_SKETCH_BORDER 0.482
#define TOP_SKETCH_BORDER 0.13
#define BOTTOM_SKETCH_BORDER 0.87

#define WORLD_SCALE 100
#define TEXTURE_SCALE 1
#define FLOODING_FACTOR 0.33

#define CULLING_ANGLE 45